#requires -Version 5.1
<#
.SYNOPSIS
    Regenerate crates/ui/ui/icons.slint from the staged reference icons.

.DESCRIPTION
    Run scripts/stage-reference-assets.ps1 first. The generated component
    exposes one if-branch per SVG file so that @image-url stays static.
#>
[CmdletBinding()]
param(
    [string]$IconsDir,
    [string]$OutFile
)

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
if (-not $IconsDir) { $IconsDir = Join-Path $repoRoot 'crates\ui\ui\assets\icons' }
if (-not $OutFile) { $OutFile = Join-Path $repoRoot 'crates\ui\ui\icons.slint' }

$icons = Get-ChildItem -LiteralPath $IconsDir -Filter *.svg | Sort-Object Name
if ($icons.Count -eq 0) {
    throw "no icons found in $IconsDir; run scripts/stage-reference-assets.ps1 first"
}

$lines = @()
$lines += '// Icon component. Generated by scripts/gen-icons.ps1 from the staged reference set.'
$lines += '// Replace the reference assets with original artwork before release.'
$lines += 'import { Theme } from "theme.slint";'
$lines += ''
$lines += 'export component Icon {'
$lines += '    in property <string> name;'
$lines += '    in property <length> icon-size: 24px;'
$lines += '    in property <color> tint: Theme.on-surface;'
$lines += '    width: icon-size;'
$lines += '    height: icon-size;'
foreach ($icon in $icons) {
    $name = $icon.BaseName
    $lines += "    if name == `"$name`": Image { width: parent.width; height: parent.height; source: @image-url(`"assets/icons/$($icon.Name)`"); colorize: tint; image-fit: contain; }"
}
$lines += '}'

Set-Content -LiteralPath $OutFile -Value $lines -Encoding UTF8
Write-Host "Wrote $OutFile with $($icons.Count) icons"
